version: '3'

services:
  app:
    image: chatgpt-web # 总是使用latest,更新时重新pull该tag镜像即可
    ports:
      - 3002:3002
    environment:
      # 二选一
      OPENAI_API_KEY:
      # 二选一
      OPENAI_ACCESS_TOKEN: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJodXhpYW95b3U4ODhAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImdlb2lwX2NvdW50cnkiOiJBRSJ9LCJodHRwczovL2FwaS5vcGVuYWkuY29tL2F1dGgiOnsidXNlcl9pZCI6InVzZXItZEpjdllIbHFhaHVuamo0YTQxWVliWExOIn0sImlzcyI6Imh0dHBzOi8vYXV0aDAub3BlbmFpLmNvbS8iLCJzdWIiOiJhdXRoMHw2M2U0OTY0YjAxNzY1NDdhY2RmZjliMWUiLCJhdWQiOlsiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS92MSIsImh0dHBzOi8vb3BlbmFpLm9wZW5haS5hdXRoMGFwcC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjc4MDExMjg0LCJleHAiOjE2NzkyMjA4ODQsImF6cCI6IlRkSkljYmUxNldvVEh0Tjk1bnl5d2g1RTR5T282SXRHIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCBtb2RlbC5yZWFkIG1vZGVsLnJlcXVlc3Qgb3JnYW5pemF0aW9uLnJlYWQgb2ZmbGluZV9hY2Nlc3MifQ.11ypyUBwGTp01b2Huo6_9OJzNALOA1eSRSzKtO1PpoLSwsRbwKobKoDq5Esgqly6wSE_cy1kVM9YPi_C0gP4PnbuPnJX7m8mMuBhmhE0QQ0zh01Cv6gGWRhXm3BuBnk5Cf5HQR7yCmJjrZNvDKyXv7qXIjd0r2A7Vr3Go4cdNuLmAEw0_q7_kixKU2s0dYt3Oiz1_rH_r3tHU2sbsu_cchiCtoZJttIjvtgMsCIKg32xlpqnd6RNW2GUopxxOwTXUdOciXkRWXZ2Y_ydzancpTrE8aT0XCoxkMZBV_uWVDOvcrv_E1w-P4M-G0yw_DTchkf4Nv6J5WefdJaILkHfew
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_BASE_URL:
      # 反向代理，可选
      API_REVERSE_PROXY:
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 60000
      # Socks代理，可选，和 SOCKS_PROXY_PORT 一起时生效
      SOCKS_PROXY_HOST:
      # Socks代理端口，可选，和 SOCKS_PROXY_HOST 一起时生效
      SOCKS_PROXY_PORT:
  nginx:
    build: nginx
    image: chatgpt/nginx
    ports:
      - '80:80'
    expose:
      - '80'
    volumes:
      - ./nginx/html/:/etc/nginx/html/
    links:
      - app
