version: '3'

services:
  app:
    image: chatgpt-web # 总是使用latest,更新时重新pull该tag镜像即可
    ports:
      - 3002:3002
    environment:
      # 二选一
      OPENAI_API_KEY: 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
      # 二选一
      OPENAI_ACCESS_TOKEN:
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_BASE_URL:
      # 反向代理，可选
      API_REVERSE_PROXY:
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 60000
      # Socks代理，可选，和 SOCKS_PROXY_PORT 一起时生效
      SOCKS_PROXY_HOST:
      # Socks代理端口，可选，和 SOCKS_PROXY_HOST 一起时生效
      SOCKS_PROXY_PORT:
  nginx:
    build: nginx
    image: chatgpt/nginx
    ports:
      - '80:80'
    expose:
      - '80'
    volumes:
      - ./nginx/html/:/etc/nginx/html/
    links:
      - app
